insert into PRODUCTS (product_name, color) values ('Fender Stratocaster', 'Sunburst');
insert into PRODUCTS (product_name, color) values ('Fender Telecaster', 'White');
insert into PRODUCTS (product_name, color) values ('Gibson Les Paul', 'Black');
insert into PRODUCTS (product_name, color) values ('Gibson SG', 'Red');
insert into PRODUCTS (product_name, color) values ('Gibson Explorer', 'Natural');
insert into PRODUCTS (product_name, color) values ('PRS Custom 24', 'Blue');
insert into PRODUCTS (product_name, color) values ('Martin D-28', 'Rosewood');
insert into PRODUCTS (product_name, color) values ('Rickenbacker 330', 'Fireglo');
insert into PRODUCTS (product_name, color) values ('Gretsch G6136T-59GE', 'White');
insert into PRODUCTS (product_name, color) values ('Esp Eclipse', 'Black');

insert into WAREHOUSES (warehouse_location, number_of_items, max_capacity) values ('Northeast', 400, 500);
insert into WAREHOUSES (warehouse_location, number_of_items, max_capacity) values ('South', 450, 500);
insert into WAREHOUSES (warehouse_location, number_of_items, max_capacity) values ('West', 350, 500);

insert into ITEMS (product_id, warehouse_id, item_quantity) values (1, 1, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (1, 2, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (1, 3, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (2, 1, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (2, 2, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (3, 1, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (3, 2, 50);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (3, 3, 50);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (4, 1, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (5, 2, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (6, 3, 100);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (7, 2, 50);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (8, 3, 50);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (9, 2, 50);
insert into ITEMS (product_id, warehouse_id, item_quantity) values (10, 3, 50);